### ISSUE TITLE
[BUG]: Doesn't extend to the edge on mod version 1.1.1

### ISSUE THREAD

**Issue by MaixGit** [KessokuTeaTime/Edgeless-Chat-Screen#5] opened 2024-04-07 02:29 UTC
### Which Mod Loader are You Using?

Fabric

### What Happened?

The chat doesn't fully fill the left and right side of the screen, it only extends fully downwards, image below.
![image](https://github.com/KessokuTeaTime/Edgeless-Chat-Screen/assets/43832909/ba30e4d1-4c85-41cc-ad96-4c9119f3591e)

### What Should Happen?

This isn't an incompatibility or anything because the mod works just fine with the same minecraft instance but mod version 1.0.2

### Steps to Reproduce

Use the latest version of the mod (1.1.1)

### Crash Log

No mention of edgelesschatscreen (apart from fabric loading it)

**Comment by KrLite** [comment] 2024-04-07 11:58
This was caused by a wrong merge commit that brought 1.19 mixin codes to 1.20+. Fixed in [`v1.1.2`](https://modrinth.com/mod/edgeless-chat-screen/version/1.1.2-fabric1.20).

**Closed as completed by KrLite** 2024-04-07 11:58 UTC
Labels: bug
